<!DOCTYPE html>
<html lang="en-us">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    
    <title>Kyle Binder  | Red Light Violations in Chicago</title>
    <meta name="HandheldFriendly" content="True">
    <meta name="MobileOptimized" content="320">

    <meta name="viewport" content="width=device-width,minimum-scale=1">
    <meta name="generator" content="Hugo 0.36.1" />
    
    
      <META NAME="ROBOTS" CONTENT="NOINDEX, NOFOLLOW">
    

    <link href='/dist/main.css' rel='stylesheet' type="text/css" />
    
      
    

    

    <meta property="og:title" content="Red Light Violations in Chicago" />
<meta property="og:description" content="In this post, we’ll explore the Red Light Camera Violations dataset accessed through the Chicago Data Portal, provided by the City of Chicago. This is just one of numerous datasets available through the portal; topics range from building permits to divvy bikes to crime data, weather data, and many more.
We can use the Socrata Open Data API to pull down and analyze the dataset.1 Lucky for us, developers at the City of Chicago have written an R package called RSocrata that allows for easy interaction with Socrata datasets in a few simple functions." />
<meta property="og:type" content="article" />
<meta property="og:url" content="/post/red-light-violations-in-chicago/" />



<meta property="article:published_time" content="2018-03-30T00:00:00&#43;00:00"/>

<meta property="article:modified_time" content="2018-03-30T00:00:00&#43;00:00"/>











<meta itemprop="name" content="Red Light Violations in Chicago">
<meta itemprop="description" content="In this post, we’ll explore the Red Light Camera Violations dataset accessed through the Chicago Data Portal, provided by the City of Chicago. This is just one of numerous datasets available through the portal; topics range from building permits to divvy bikes to crime data, weather data, and many more.
We can use the Socrata Open Data API to pull down and analyze the dataset.1 Lucky for us, developers at the City of Chicago have written an R package called RSocrata that allows for easy interaction with Socrata datasets in a few simple functions.">


<meta itemprop="datePublished" content="2018-03-30T00:00:00&#43;00:00" />
<meta itemprop="dateModified" content="2018-03-30T00:00:00&#43;00:00" />
<meta itemprop="wordCount" content="1061">



<meta itemprop="keywords" content="R,Chicago Data Portal," />
<meta name="twitter:card" content="summary"/>
<meta name="twitter:title" content="Red Light Violations in Chicago"/>
<meta name="twitter:description" content="In this post, we’ll explore the Red Light Camera Violations dataset accessed through the Chicago Data Portal, provided by the City of Chicago. This is just one of numerous datasets available through the portal; topics range from building permits to divvy bikes to crime data, weather data, and many more.
We can use the Socrata Open Data API to pull down and analyze the dataset.1 Lucky for us, developers at the City of Chicago have written an R package called RSocrata that allows for easy interaction with Socrata datasets in a few simple functions."/>

  </head>

  <body class="ma0 avenir bg-near-white">

    
   
  

  
  
  <header class="cover bg-top" style="background-image: url('/images/red_light.jpg');">
    <div class="pb3-m pb6-l bg-black-60">
      <nav class="pv3 ph3 ph4-ns" role="navigation">
  <div class="flex-l justify-between items-center center">
    <a href="/" class="f3 fw2 hover-white no-underline white-90 dib">
      Kyle Binder
    </a>
    <div class="flex-l items-center">
      
        <ul class="pl0 mr3">
          
          <li class="list f5 f4-ns fw4 dib pr3">
            <a class="hover-white no-underline white-90" href="/about/" title="About page">
              About
            </a>
          </li>
          
          <li class="list f5 f4-ns fw4 dib pr3">
            <a class="hover-white no-underline white-90" href="/post/" title="Blog Posts page">
              Blog Posts
            </a>
          </li>
          
          <li class="list f5 f4-ns fw4 dib pr3">
            <a class="hover-white no-underline white-90" href="/cv/" title="CV page">
              CV
            </a>
          </li>
          
        </ul>
      
      






  <a href="https://www.linkedin.com/in/kyle-binder-460a7b84/" class="link-transition linkedin link dib z-999 pt3 pt0-l mr2" title="LinkedIn link">
    <svg  height="32px"  style="enable-background:new 0 0 65 65;" version="1.1" viewBox="0 0 65 65" width="32px" xml:space="preserve" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
  <path d="M50.837,48.137V36.425c0-6.275-3.35-9.195-7.816-9.195  c-3.604,0-5.219,1.983-6.119,3.374V27.71h-6.79c0.09,1.917,0,20.427,0,20.427h6.79V36.729c0-0.609,0.044-1.219,0.224-1.655  c0.49-1.22,1.607-2.483,3.482-2.483c2.458,0,3.44,1.873,3.44,4.618v10.929H50.837z M22.959,24.922c2.367,0,3.842-1.57,3.842-3.531  c-0.044-2.003-1.475-3.528-3.797-3.528s-3.841,1.524-3.841,3.528c0,1.961,1.474,3.531,3.753,3.531H22.959z M34,64  C17.432,64,4,50.568,4,34C4,17.431,17.432,4,34,4s30,13.431,30,30C64,50.568,50.568,64,34,64z M26.354,48.137V27.71h-6.789v20.427  H26.354z" style="fill-rule:evenodd;clip-rule:evenodd;fill:;"/>
</svg>

  </a>


  <a href="https://github.com/kylebinder" class="link-transition github link dib z-999 pt3 pt0-l mr2" title="Github link">
    <svg  height="32px"  style="enable-background:new 0 0 512 512;" version="1.1" viewBox="0 0 512 512" width="32px" xml:space="preserve" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" >
  <path d="M256,32C132.3,32,32,134.8,32,261.7c0,101.5,64.2,187.5,153.2,217.9c11.2,2.1,15.3-5,15.3-11.1   c0-5.5-0.2-19.9-0.3-39.1c-62.3,13.9-75.5-30.8-75.5-30.8c-10.2-26.5-24.9-33.6-24.9-33.6c-20.3-14.3,1.5-14,1.5-14   c22.5,1.6,34.3,23.7,34.3,23.7c20,35.1,52.4,25,65.2,19.1c2-14.8,7.8-25,14.2-30.7c-49.7-5.8-102-25.5-102-113.5   c0-25.1,8.7-45.6,23-61.6c-2.3-5.8-10-29.2,2.2-60.8c0,0,18.8-6.2,61.6,23.5c17.9-5.1,37-7.6,56.1-7.7c19,0.1,38.2,2.6,56.1,7.7   c42.8-29.7,61.5-23.5,61.5-23.5c12.2,31.6,4.5,55,2.2,60.8c14.3,16.1,23,36.6,23,61.6c0,88.2-52.4,107.6-102.3,113.3   c8,7.1,15.2,21.1,15.2,42.5c0,30.7-0.3,55.5-0.3,63c0,6.1,4,13.3,15.4,11C415.9,449.1,480,363.1,480,261.7   C480,134.8,379.7,32,256,32z"/>
</svg>

  </a>


    </div>
  </div>
</nav>

      <div class="tc-l pv6 ph3 ph4-ns">
        <h1 class="f2 f1-l fw2 white-90 mb0 lh-title">Red Light Violations in Chicago</h1>
        
      </div>
    </div>
  </header>


<link rel="stylesheet" href="/dist/github-gist.css" rel="stylesheet" id="theme-stylesheet">
<script src="/dist/highlight.pack.js"></script>
<script>hljs.initHighlightingOnLoad();</script>

    <main class="pb7" role="main">
      
  <div class="flex-l mt2 mw8 center">
    <article class="center cf pv5 ph3 ph4-ns mw7">
      <p class="f6 b helvetica tracked">
        
        POST
      </p>
      <h1 class="f1 athelas">
        Red Light Violations in Chicago
      </h1>
        
        
      <time class="f6 mv4 dib tracked" datetime="2018-03-30T00:00:00Z">
        March 30, 2018
      </time>
      <section class="nested-copy-line-height lh-copy serif f4 nested-links nested-img mid-gray">
        <p>In this post, we’ll explore the Red Light Camera Violations dataset accessed through the <a href="https://data.cityofchicago.org/">Chicago Data Portal</a>, provided by the City of Chicago. This is just one of numerous datasets available through the portal; topics range from building permits to divvy bikes to crime data, weather data, and many more.</p>
<p>We can use the <a href="https://dev.socrata.com/">Socrata Open Data API</a> to pull down and analyze the dataset.<a href="#fn1" class="footnoteRef" id="fnref1"><sup>1</sup></a> Lucky for us, developers at the City of Chicago have written an R package called RSocrata that allows for easy interaction with Socrata datasets in a few simple functions.</p>
<p>You can install the latest version of RSocrata available via GitHub:</p>
<pre class="r"><code>devtools::install_github(&quot;RSocrata&quot;)</code></pre>
<p>We’ll use the following packages in this post:</p>
<pre class="r"><code>library(RSocrata)
library(dplyr)
library(ggplot2)
library(ggthemes)
library(tidyr)
library(knitr)
library(ggmap)
library(ggrepel)</code></pre>
<p>Now we can load the red light dataset by passing a Socrata-valid url, <a href="https://data.cityofchicago.org/Transportation/Red-Light-Camera-Violations/spqx-js37">found here</a> using the export functionality, to the <code>read.socrata()</code> function. The data are available from July 2014 to present and contain a number of characterics for each recorded red light violation in the city, including the location (address, intersection, coordinates), camera identifier, and violation date.</p>
<pre class="r"><code>red_light_data &lt;- read.socrata(&quot;https://data.cityofchicago.org/resource/twfh-866z.json&quot;)
head(as_tibble(red_light_data))</code></pre>
<pre><code>## # A tibble: 6 x 11
##                   address camera_id                         intersection
##                     &lt;chr&gt;     &lt;chr&gt;                                &lt;chr&gt;
## 1 3100 S DR MARTIN L KING      2121 31ST ST AND MARTIN LUTHER KING DRIVE
## 2      0 S CENTRAL AVENUE      1751                  MADISON AND CENTRAL
## 3     1600 N HOMAN AVENUE      1771              HOMAN/KIMBALL AND NORTH
## 4  5200 W IRVING PARK ROA      1533              IRVING PARK AND LARAMIE
## 5         0 N ASHLAND AVE      1911                  ASHLAND AND MADISON
## 6  4700 W IRVING PARK ROA      2763           IRVING PARK AND KILPATRICK
## # ... with 8 more variables: violation_date &lt;dttm&gt;, violations &lt;chr&gt;,
## #   latitude &lt;chr&gt;, location.type &lt;chr&gt;, location.coordinates &lt;list&gt;,
## #   longitude &lt;chr&gt;, x_coordinate &lt;chr&gt;, y_coordinate &lt;chr&gt;</code></pre>
<p>Let’s construct a time series from the daily count of total red light camera violations in the city of Chicago and plot it.</p>
<pre class="r"><code># convert (violations, latitude, and longitude to numeric)
red_light_data &lt;- red_light_data %&gt;%
  mutate(violations = as.numeric(violations),
         latitude = as.numeric(latitude),
         longitude = as.numeric(longitude))

# total daily violations
daily_count &lt;- red_light_data %&gt;%
  group_by(violation_date) %&gt;%
  summarise(n_violations = sum(violations)) %&gt;%
  # compute seven day moving average
  mutate(ma_n_violations = (n_violations + lag(n_violations, 1)
         + lag(n_violations, 2) + lag(n_violations, 3) + lag(n_violations, 4)
         + lag(n_violations, 5) + lag(n_violations, 6)) / 7) %&gt;%
  gather(type, count, -violation_date)

# make plot
ggplot(data = daily_count, 
       aes(x = violation_date, y = count, group = type, colour = type)) +
  geom_line(aes(alpha = type)) +
  scale_alpha_manual(values = c(1, 0.5), guide = FALSE) +
  scale_colour_manual(values = c(&quot;orange&quot;, &quot;darkblue&quot;),
                      labels = c(&quot;7-day Moving Average&quot;, 
                                 &quot;Count of Violations&quot;),
                      guide = guide_legend(reverse = TRUE)) +
  xlab(&quot;Date&quot;) +
  ylab(&quot;No. of Violations&quot;) +
  ggtitle(&quot;Daily Red Light Camera Violations across Chicago&quot;) +
  theme_few() +
  theme(legend.title = element_blank(),
        legend.position = c(0.8, 0.9))</code></pre>
<p><img src="/post/2018-02-19-red-light-violations-in-chicago_files/figure-html/time_plot-1.png" width="672" /></p>
<p>Day-to-day total red light violations in Chicago appear to be highly volatile. A seasonal pattern is also present. Intuitively, violations seems to be higher in the summer and lower in the winter. There is one day in early 2015 that appears to be a major outlier; let’s take a peek.</p>
<pre class="r"><code>filter(daily_count, count == min(count, na.rm = TRUE))</code></pre>
<pre><code>## # A tibble: 1 x 3
##   violation_date         type count
##           &lt;dttm&gt;        &lt;chr&gt; &lt;dbl&gt;
## 1     2015-02-01 n_violations   385</code></pre>
<p>Anything interesting about February 1st, 2015? Chicago saw a February record snowfall of <a href="https://www.weather.gov/lot/2015_Feb01_Snow">16.2 inches</a> on that day! The snowy conditions may explain the low number of red light camera violations… in fact it seems a bit surprising that as many as 385 were ticketed in 16 inches of snow. Generally speaking, weather conditions may be a good predictor of red light violations on a given day.</p>
<p>Which red light camera locations dole out the highest number of violations? Some intersections have more than one camera, but we’ll group those together here. And because it’s likely that some locations have had red light cameras longer than others, we’ll look at average number of violations per day by location.</p>
<pre class="r"><code>loc_summary &lt;- red_light_data %&gt;%
  group_by(intersection) %&gt;%
  # assign same lat/long to given intersection to group all cameras at intersection together
  mutate(latitude = first(latitude[is.na(latitude) == FALSE]),
         longitude = first(longitude[is.na(longitude) == FALSE])) %&gt;%
  group_by(intersection, longitude, latitude) %&gt;%
  summarise(n_violations = sum(violations),
            days = length(unique(violation_date))) %&gt;%
  mutate(avg_violations = n_violations/days) %&gt;%
  ungroup() %&gt;%
  arrange(desc(avg_violations))

kable(head(loc_summary %&gt;% 
             select(intersection, n_violations, days, avg_violations), 
           10))</code></pre>
<table>
<thead>
<tr class="header">
<th align="left">intersection</th>
<th align="right">n_violations</th>
<th align="right">days</th>
<th align="right">avg_violations</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">CICERO AND I55</td>
<td align="right">72014</td>
<td align="right">1100</td>
<td align="right">65.46727</td>
</tr>
<tr class="even">
<td align="left">LAKE SHORE DR AND BELMONT</td>
<td align="right">71886</td>
<td align="right">1355</td>
<td align="right">53.05240</td>
</tr>
<tr class="odd">
<td align="left">VAN BUREN AND WESTERN</td>
<td align="right">55824</td>
<td align="right">1355</td>
<td align="right">41.19852</td>
</tr>
<tr class="even">
<td align="left">LAFAYETTE AND 87TH</td>
<td align="right">46588</td>
<td align="right">1345</td>
<td align="right">34.63792</td>
</tr>
<tr class="odd">
<td align="left">CALIFORNIA AND DIVERSEY</td>
<td align="right">44974</td>
<td align="right">1355</td>
<td align="right">33.19114</td>
</tr>
<tr class="even">
<td align="left">STATE AND 79TH</td>
<td align="right">44710</td>
<td align="right">1352</td>
<td align="right">33.06953</td>
</tr>
<tr class="odd">
<td align="left">STONEY ISLAND AND 76TH</td>
<td align="right">41728</td>
<td align="right">1353</td>
<td align="right">30.84109</td>
</tr>
<tr class="even">
<td align="left">WENTWORTH AND GARFIELD</td>
<td align="right">39695</td>
<td align="right">1355</td>
<td align="right">29.29520</td>
</tr>
<tr class="odd">
<td align="left">ARCHER AND CICERO</td>
<td align="right">38332</td>
<td align="right">1321</td>
<td align="right">29.01741</td>
</tr>
<tr class="even">
<td align="left">99TH AND HALSTED</td>
<td align="right">33609</td>
<td align="right">1352</td>
<td align="right">24.85873</td>
</tr>
</tbody>
</table>
<p>On the surface, not one part of the city seems to dominate in terms of red light violations. The North, South, and West sides are all represented in the top 10. We can take this a step further by visualing the spatial distribution of red light violations in Chicago using the <code>ggmap</code> package. As seen below, the distribution of average violations per day is heavily right-skewed, so we’ll map the violations on a log scale.</p>
<pre class="r"><code>ggplot(data = loc_summary, aes(x = avg_violations)) + 
  geom_histogram(binwidth = 3, fill = &quot;darkblue&quot;, colour = &quot;orange&quot;) +
  xlab(&quot;Average No. of Red Light Violations per day&quot;) +
  ylab(&quot;Count&quot;) +
  ggtitle(&quot;Distribution of Mean Red Light Violations Per Day across Locations &quot;) +
  theme_few()</code></pre>
<p><img src="/post/2018-02-19-red-light-violations-in-chicago_files/figure-html/avg_violations_hist-1.png" width="672" /></p>
<pre class="r"><code>map &lt;- ggmap(get_map(location = &quot;chicago, illinois&quot;, zoom = 11, color = &quot;bw&quot;)) +
  geom_point(data = loc_summary, aes(x = longitude, 
                                     y = latitude,
                                     colour = log(avg_violations)),
             alpha = 1) +
  scale_colour_gradient(low = &quot;lightyellow&quot;, high = &quot;darkred&quot;,
                        name = &quot;Log of Avg. Violations Per Day&quot;) +
  theme(axis.title.x = element_blank(),
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank(),
        axis.ticks.y = element_blank(),
        axis.text.y = element_blank(),
        axis.title.y = element_blank(),
        legend.position = &quot;top&quot;)

map</code></pre>
<p><img src="/post/2018-02-19-red-light-violations-in-chicago_files/figure-html/camera_map-1.png" width="672" /></p>
<p>As shown above, the intersection at Cicero and I55 shows the darkest shade of red (65.47 violations per day on average). Let’s add some text labels for the top 5 intersections by average number of violations to make this easier to see.</p>
<pre class="r"><code>map +  
  geom_label_repel(data = head(loc_summary, 5), 
                   aes(x = longitude,
                       y = latitude,
                       label = intersection),
                   size = 2,
                   min.segment.length = 0)</code></pre>
<p><img src="/post/2018-02-19-red-light-violations-in-chicago_files/figure-html/camera%20map%20with%20label-1.png" width="672" /></p>
<p>In the next post, we’ll build a simple predictive model for daily red light violations in Chicago.</p>
<div class="footnotes">
<hr />
<ol>
<li id="fn1"><p>Note that data from institutions around the world, many many more than just the City of Chicago, is available through Socrata.<a href="#fnref1">↩</a></p></li>
</ol>
</div>

      </section>
      

  
  
  
  
  


    </article>
    <div class="ph3 mt2 mt6-ns">
      








    </div>
  </div>

    </main>
    <footer class="bg-near-black bottom-0 w-100 pa3" role="contentinfo">
  <div class="flex justify-between">
  <a class="f4 fw4 hover-white no-underline white-70 dn dib-ns pv2 ph3" href="/" >
    &copy; 2018 Kyle Binder
  </a>
  






  <a href="https://www.linkedin.com/in/kyle-binder-460a7b84/" class="link-transition linkedin link dib z-999 pt3 pt0-l mr2" title="LinkedIn link">
    <svg  height="32px"  style="enable-background:new 0 0 65 65;" version="1.1" viewBox="0 0 65 65" width="32px" xml:space="preserve" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
  <path d="M50.837,48.137V36.425c0-6.275-3.35-9.195-7.816-9.195  c-3.604,0-5.219,1.983-6.119,3.374V27.71h-6.79c0.09,1.917,0,20.427,0,20.427h6.79V36.729c0-0.609,0.044-1.219,0.224-1.655  c0.49-1.22,1.607-2.483,3.482-2.483c2.458,0,3.44,1.873,3.44,4.618v10.929H50.837z M22.959,24.922c2.367,0,3.842-1.57,3.842-3.531  c-0.044-2.003-1.475-3.528-3.797-3.528s-3.841,1.524-3.841,3.528c0,1.961,1.474,3.531,3.753,3.531H22.959z M34,64  C17.432,64,4,50.568,4,34C4,17.431,17.432,4,34,4s30,13.431,30,30C64,50.568,50.568,64,34,64z M26.354,48.137V27.71h-6.789v20.427  H26.354z" style="fill-rule:evenodd;clip-rule:evenodd;fill:;"/>
</svg>

  </a>


  <a href="https://github.com/kylebinder" class="link-transition github link dib z-999 pt3 pt0-l mr2" title="Github link">
    <svg  height="32px"  style="enable-background:new 0 0 512 512;" version="1.1" viewBox="0 0 512 512" width="32px" xml:space="preserve" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" >
  <path d="M256,32C132.3,32,32,134.8,32,261.7c0,101.5,64.2,187.5,153.2,217.9c11.2,2.1,15.3-5,15.3-11.1   c0-5.5-0.2-19.9-0.3-39.1c-62.3,13.9-75.5-30.8-75.5-30.8c-10.2-26.5-24.9-33.6-24.9-33.6c-20.3-14.3,1.5-14,1.5-14   c22.5,1.6,34.3,23.7,34.3,23.7c20,35.1,52.4,25,65.2,19.1c2-14.8,7.8-25,14.2-30.7c-49.7-5.8-102-25.5-102-113.5   c0-25.1,8.7-45.6,23-61.6c-2.3-5.8-10-29.2,2.2-60.8c0,0,18.8-6.2,61.6,23.5c17.9-5.1,37-7.6,56.1-7.7c19,0.1,38.2,2.6,56.1,7.7   c42.8-29.7,61.5-23.5,61.5-23.5c12.2,31.6,4.5,55,2.2,60.8c14.3,16.1,23,36.6,23,61.6c0,88.2-52.4,107.6-102.3,113.3   c8,7.1,15.2,21.1,15.2,42.5c0,30.7-0.3,55.5-0.3,63c0,6.1,4,13.3,15.4,11C415.9,449.1,480,363.1,480,261.7   C480,134.8,379.7,32,256,32z"/>
</svg>

  </a>


  </div>
</footer>

    <script src="/dist/app.bundle.js" async></script>

  </body>
</html>
